import Head from "next/head";
import Header from "@/components/Header";
import Content from "@/components/Content";

import "bootstrap/dist/css/bootstrap.min.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>TechInterview</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <main>
        <Content />
      </main>
    </>
  );
}

